name: book

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - network
    environment:
      - PORT=4026
    volumes:
      - type: bind
        source: ./books
        target: /root/books
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.book.rule=Host(`book.poetry.software`)"
      - "traefik.http.routers.book.entrypoints=websecure"
      - "traefik.http.routers.book.tls.certresolver=certresolver"
      - "traefik.http.services.book.loadbalancer.server.port=4026"

networks:
  network:
    driver: bridge
