name: book

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - network
    environment:
      - PORT=4026

networks:
  network:
    driver: bridge
