name: book

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - network
    environment:
      - PORT=4026
    volumes:
      - type: bind
        source: ./books
        target: /root/books

networks:
  network:
    driver: bridge
